//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace artis_lab.ARTISLAB {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.radford.edu/ArtisLab", ConfigurationName="ARTISLAB.ArtisLabInfoServiceSoap")]
    public interface ArtisLabInfoServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/logIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string logIn(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/logIn", ReplyAction="*")]
        System.Threading.Tasks.Task<string> logInAsync(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/logOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string logOut(string strToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/logOut", ReplyAction="*")]
        System.Threading.Tasks.Task<string> logOutAsync(string strToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/getResUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        artis_lab.ARTISLAB.ResUser getResUser(string username, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/getResUser", ReplyAction="*")]
        System.Threading.Tasks.Task<artis_lab.ARTISLAB.ResUser> getResUserAsync(string username, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/getTopUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getTopUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/getTopUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getTopUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/getResourceUsage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getResourceUsage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/getResourceUsage", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getResourceUsageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/getResources", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getResources();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/getResources", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getResourcesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/getPrivLevels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getPrivLevels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/getPrivLevels", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getPrivLevelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/saveResUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string saveResUser(artis_lab.ARTISLAB.ResUser ResUserToSave, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/saveResUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> saveResUserAsync(artis_lab.ARTISLAB.ResUser ResUserToSave, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/insertResUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string insertResUser(artis_lab.ARTISLAB.ResUser ResUserToSave, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/insertResUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> insertResUserAsync(artis_lab.ARTISLAB.ResUser ResUserToSave, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/deleteResUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string deleteResUser(string UsernameToDelete, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/deleteResUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> deleteResUserAsync(string UsernameToDelete, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/usernameContains", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable usernameContains(string strToFind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/usernameContains", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> usernameContainsAsync(string strToFind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/usernameStartsWith", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable usernameStartsWith(string strToFind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/usernameStartsWith", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> usernameStartsWithAsync(string strToFind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/notesContains", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable notesContains(string strToFind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/notesContains", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> notesContainsAsync(string strToFind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/getSemesterNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] getSemesterNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/getSemesterNames", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> getSemesterNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/getResUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getResUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/ArtisLab/getResUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getResUsersAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.radford.edu/ArtisLab")]
    public partial class ResUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string privLevelField;
        
        private System.DateTime createDateField;
        
        private string notesField;
        
        private string dbMessageField;
        
        private System.Data.DataTable recentReservationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PrivLevel {
            get {
                return this.privLevelField;
            }
            set {
                this.privLevelField = value;
                this.RaisePropertyChanged("PrivLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("Notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string dbMessage {
            get {
                return this.dbMessageField;
            }
            set {
                this.dbMessageField = value;
                this.RaisePropertyChanged("dbMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.Data.DataTable RecentReservations {
            get {
                return this.recentReservationsField;
            }
            set {
                this.recentReservationsField = value;
                this.RaisePropertyChanged("RecentReservations");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ArtisLabInfoServiceSoapChannel : artis_lab.ARTISLAB.ArtisLabInfoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArtisLabInfoServiceSoapClient : System.ServiceModel.ClientBase<artis_lab.ARTISLAB.ArtisLabInfoServiceSoap>, artis_lab.ARTISLAB.ArtisLabInfoServiceSoap {
        
        public ArtisLabInfoServiceSoapClient() {
        }
        
        public ArtisLabInfoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArtisLabInfoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtisLabInfoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtisLabInfoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string logIn(string strUsername, string strPassword) {
            return base.Channel.logIn(strUsername, strPassword);
        }
        
        public System.Threading.Tasks.Task<string> logInAsync(string strUsername, string strPassword) {
            return base.Channel.logInAsync(strUsername, strPassword);
        }
        
        public string logOut(string strToken) {
            return base.Channel.logOut(strToken);
        }
        
        public System.Threading.Tasks.Task<string> logOutAsync(string strToken) {
            return base.Channel.logOutAsync(strToken);
        }
        
        public artis_lab.ARTISLAB.ResUser getResUser(string username, string token) {
            return base.Channel.getResUser(username, token);
        }
        
        public System.Threading.Tasks.Task<artis_lab.ARTISLAB.ResUser> getResUserAsync(string username, string token) {
            return base.Channel.getResUserAsync(username, token);
        }
        
        public System.Data.DataTable getTopUsers() {
            return base.Channel.getTopUsers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getTopUsersAsync() {
            return base.Channel.getTopUsersAsync();
        }
        
        public System.Data.DataTable getResourceUsage() {
            return base.Channel.getResourceUsage();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getResourceUsageAsync() {
            return base.Channel.getResourceUsageAsync();
        }
        
        public System.Data.DataTable getResources() {
            return base.Channel.getResources();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getResourcesAsync() {
            return base.Channel.getResourcesAsync();
        }
        
        public System.Data.DataTable getPrivLevels() {
            return base.Channel.getPrivLevels();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getPrivLevelsAsync() {
            return base.Channel.getPrivLevelsAsync();
        }
        
        public string saveResUser(artis_lab.ARTISLAB.ResUser ResUserToSave, string Token) {
            return base.Channel.saveResUser(ResUserToSave, Token);
        }
        
        public System.Threading.Tasks.Task<string> saveResUserAsync(artis_lab.ARTISLAB.ResUser ResUserToSave, string Token) {
            return base.Channel.saveResUserAsync(ResUserToSave, Token);
        }
        
        public string insertResUser(artis_lab.ARTISLAB.ResUser ResUserToSave, string Token) {
            return base.Channel.insertResUser(ResUserToSave, Token);
        }
        
        public System.Threading.Tasks.Task<string> insertResUserAsync(artis_lab.ARTISLAB.ResUser ResUserToSave, string Token) {
            return base.Channel.insertResUserAsync(ResUserToSave, Token);
        }
        
        public string deleteResUser(string UsernameToDelete, string Token) {
            return base.Channel.deleteResUser(UsernameToDelete, Token);
        }
        
        public System.Threading.Tasks.Task<string> deleteResUserAsync(string UsernameToDelete, string Token) {
            return base.Channel.deleteResUserAsync(UsernameToDelete, Token);
        }
        
        public System.Data.DataTable usernameContains(string strToFind) {
            return base.Channel.usernameContains(strToFind);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> usernameContainsAsync(string strToFind) {
            return base.Channel.usernameContainsAsync(strToFind);
        }
        
        public System.Data.DataTable usernameStartsWith(string strToFind) {
            return base.Channel.usernameStartsWith(strToFind);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> usernameStartsWithAsync(string strToFind) {
            return base.Channel.usernameStartsWithAsync(strToFind);
        }
        
        public System.Data.DataTable notesContains(string strToFind) {
            return base.Channel.notesContains(strToFind);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> notesContainsAsync(string strToFind) {
            return base.Channel.notesContainsAsync(strToFind);
        }
        
        public string[] getSemesterNames() {
            return base.Channel.getSemesterNames();
        }
        
        public System.Threading.Tasks.Task<string[]> getSemesterNamesAsync() {
            return base.Channel.getSemesterNamesAsync();
        }
        
        public System.Data.DataTable getResUsers() {
            return base.Channel.getResUsers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getResUsersAsync() {
            return base.Channel.getResUsersAsync();
        }
    }
}
